// ── Report Formatters (Markdown, CSV, JSON) ─────────────────────────

// ── Format Currency ─────────────────────────────────────────────────

function formatCurrency(value, currency = "JPY") {
  if (value == null) return "-";
  const num = parseFloat(value);
  if (currency === "JPY") {
    return `¥${Math.round(num).toLocaleString()}`;
  }
  return `$${num.toFixed(2)}`;
}

function formatNumber(value) {
  if (value == null) return "-";
  return parseInt(value).toLocaleString();
}

function formatPercent(value) {
  if (value == null) return "-";
  return `${parseFloat(value).toFixed(2)}%`;
}

function formatDecimal(value, places = 2) {
  if (value == null) return "-";
  return parseFloat(value).toFixed(places);
}

// ── Markdown Table ──────────────────────────────────────────────────

function markdownTable(headers, rows) {
  const separator = headers.map(() => "---").join(" | ");
  const headerRow = headers.join(" | ");
  const dataRows = rows.map((r) => r.join(" | ")).join("\n");
  return `${headerRow}\n${separator}\n${dataRows}`;
}

// ── Format as Markdown ──────────────────────────────────────────────

export function formatAsMarkdown(report) {
  let md = `# ${report.title || "Meta Ads Report"}\n\n`;

  // Metadata
  if (report.date_range) {
    md += `**期間**: ${report.date_range.since} 〜 ${report.date_range.until}\n\n`;
  }
  if (report.generated_at) {
    md += `**生成日時**: ${new Date(report.generated_at).toLocaleString("ja-JP")}\n\n`;
  }

  md += "---\n\n";

  // Summary
  if (report.summary) {
    md += "## 📊 サマリー\n\n";
    const s = report.summary;
    md += `- **総消費額**: ${formatCurrency(s.total_spend)}\n`;
    md += `- **総インプレッション**: ${formatNumber(s.total_impressions)}\n`;
    md += `- **総クリック**: ${formatNumber(s.total_clicks)}\n`;
    md += `- **総コンバージョン**: ${formatNumber(s.total_conversions)}\n`;
    md += `- **平均CTR**: ${formatPercent(s.avg_ctr)}\n`;
    md += `- **平均CPC**: ${formatCurrency(s.avg_cpc)}\n`;
    md += `- **平均CPA**: ${formatCurrency(s.avg_cpa)}\n`;
    md += `- **平均フリクエンシー**: ${formatDecimal(s.avg_frequency)}\n\n`;
  }

  // Top performers
  if (report.top_performers) {
    md += "## 🏆 トップパフォーマー\n\n";
    md += `**基準**: ${report.top_performers.metric_label}\n\n`;
    const headers = ["順位", "名前", report.top_performers.metric_label, "消費額", "クリック"];
    const rows = report.top_performers.top.slice(0, 10).map((p, i) => [
      i + 1,
      p.name,
      formatDecimal(p.metric_value),
      formatCurrency(p.spend),
      formatNumber(p.clicks),
    ]);
    md += markdownTable(headers, rows) + "\n\n";
  }

  // Trends
  if (report.trends) {
    md += "## 📈 トレンド分析\n\n";
    md += `**トレンド**: ${report.trends.trend === "improving" ? "📈 改善中" : report.trends.trend === "declining" ? "📉 低下中" : "→ 安定"}\n\n`;
    if (report.trends.changes) {
      md += `- 消費額変化: ${report.trends.changes.spend_change_percent > 0 ? "+" : ""}${report.trends.changes.spend_change_percent}%\n`;
      md += `- クリック変化: ${report.trends.changes.click_change_percent > 0 ? "+" : ""}${report.trends.changes.click_change_percent}%\n`;
      md += `- CV変化: ${report.trends.changes.conversion_change_percent > 0 ? "+" : ""}${report.trends.changes.conversion_change_percent}%\n\n`;
    }
  }

  // Breakdown
  if (report.breakdown) {
    md += `## 📊 ${report.breakdown.breakdown_type} 別分析\n\n`;
    const headers = ["セグメント", "消費額", "シェア", "CTR", "CPA"];
    const rows = report.breakdown.segments.slice(0, 10).map((seg) => [
      seg.segment,
      formatCurrency(seg.spend),
      formatPercent(seg.spend_percent),
      formatPercent(seg.ctr),
      formatCurrency(seg.cpa),
    ]);
    md += markdownTable(headers, rows) + "\n\n";
  }

  // Recommendations
  if (report.recommendations && report.recommendations.length > 0) {
    md += "## 💡 推奨アクション\n\n";
    report.recommendations.forEach((rec, i) => {
      md += `${i + 1}. **${rec.title}**: ${rec.description}\n`;
    });
    md += "\n";
  }

  md += "---\n\n";
  md += "_Generated by Meta Report MCP Server_\n";

  return md;
}

// ── Format as CSV ───────────────────────────────────────────────────

export function formatAsCSV(data, columns) {
  if (!data || data.length === 0) return "";

  // Auto-detect columns if not provided
  if (!columns) {
    columns = Object.keys(data[0]);
  }

  // Header
  let csv = columns.join(",") + "\n";

  // Rows
  for (const row of data) {
    const values = columns.map((col) => {
      let val = row[col];
      if (val == null) return "";
      if (typeof val === "object") val = JSON.stringify(val);
      val = String(val).replace(/"/g, '""'); // Escape quotes
      return `"${val}"`;
    });
    csv += values.join(",") + "\n";
  }

  return csv;
}

// ── Format as Plain Text Table ──────────────────────────────────────

export function formatAsTextTable(data, columns) {
  if (!data || data.length === 0) return "No data";

  if (!columns) {
    columns = Object.keys(data[0]);
  }

  // Calculate column widths
  const widths = {};
  for (const col of columns) {
    widths[col] = Math.max(
      col.length,
      ...data.map((row) => String(row[col] || "").length)
    );
  }

  // Header
  let table = columns.map((col) => col.padEnd(widths[col])).join(" | ") + "\n";
  table += columns.map((col) => "-".repeat(widths[col])).join("-+-") + "\n";

  // Rows
  for (const row of data) {
    table += columns.map((col) => String(row[col] || "").padEnd(widths[col])).join(" | ") + "\n";
  }

  return table;
}

// ── Generate Recommendations ────────────────────────────────────────

export function generateRecommendations(summary, topPerformers, trends) {
  const recommendations = [];

  // High CPA warning
  if (summary?.avg_cpa > 5000) {
    recommendations.push({
      priority: "high",
      title: "高CPA改善",
      description: `平均CPA ¥${Math.round(summary.avg_cpa)} は高めです。低パフォーマンス広告セットの停止またはターゲティング見直しを検討してください。`,
    });
  }

  // Low CTR warning
  if (summary?.avg_ctr < 0.5) {
    recommendations.push({
      priority: "medium",
      title: "CTR改善",
      description: `平均CTR ${summary.avg_ctr.toFixed(2)}% は低めです。クリエイティブの刷新やコピーの見直しを推奨します。`,
    });
  }

  // High frequency
  if (summary?.avg_frequency > 3) {
    recommendations.push({
      priority: "medium",
      title: "フリクエンシー管理",
      description: `平均フリクエンシー ${summary.avg_frequency.toFixed(1)} は高めです。オーディエンス拡大またはクリエイティブ更新で広告疲弊を防ぎましょう。`,
    });
  }

  // Declining trend
  if (trends?.trend === "declining") {
    recommendations.push({
      priority: "high",
      title: "パフォーマンス低下",
      description: "パフォーマンスが低下傾向です。予算配分の見直し、A/Bテスト実施、またはキャンペーン再構築を検討してください。",
    });
  }

  // Scale top performers
  if (topPerformers?.top && topPerformers.top.length > 0) {
    const best = topPerformers.top[0];
    recommendations.push({
      priority: "medium",
      title: "勝者スケール",
      description: `「${best.name}」が最高パフォーマンスです。予算増額でさらなる成果を狙いましょう。`,
    });
  }

  return recommendations;
}
